[package]
name = "xtask"
version = "0.1.0"
authors = ["linux_china <libing.chen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
man = "0.3.0"
